version: '3.8'
services:

  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: dev
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json
    volumes:
      - ../researchapp-453819-f97cdc06708e.json:/app/gcp-key.json
    ports:
      - "8080:8080"

  bpm-service:
    build:
      context: ../python_microservice
      dockerfile: Dockerfile
    ports:
      - "5001:5000"

volumes:
  mysql_data:
