name: GCP Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decode GCP Credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_BASE64 }}" | base64 --decode > gcp-key.json

      - name: Prepare SSH Key
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy files to GCP instance
        run: |
          scp -i private_key.pem -o StrictHostKeyChecking=no gcp-key.json ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE_IP }}:/home/${{ secrets.GCP_USER }}/app/gcp-key.json
          scp -i private_key.pem -o StrictHostKeyChecking=no -r ./client ./server ./docker ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE_IP }}:/home/${{ secrets.GCP_USER }}/app/

      - name: Deploy on GCP
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.GCP_USER }}@${{ secrets.GCP_INSTANCE_IP }} << EOF
          cd /home/${{ secrets.GCP_USER }}/app/docker

          export GOOGLE_APPLICATION_CREDENTIALS=/home/${{ secrets.GCP_USER }}/app/gcp-key.json

          docker compose down
          docker compose up -d --build
          EOF

      - name: Cleanup Sensitive Files
        run: |
          rm -f private_key.pem gcp-key.json
