name: Sample Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Cleanup
        run: |
          docker system prune -a -f --filter "until=24h"

      - name: Build
        run: |
          docker compose -f docker/production.docker-compose.yml build

      - name: Deploy
        run: |
          docker compose -f docker/production.docker-compose.yml down
          docker compose -f docker/production.docker-compose.yml up -d --build